In [ ]:
import numpy as np
from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import gym
import random
from scipy.linalg import solve


In [ ]:
# np.random.seed(0)

In [ ]:
env = gym.make('CartPole-v0')

In [ ]:
env.reset()

array([-0.03954555,  0.04991983, -0.04186659, -0.00989815])

In [ ]:
env.force_mag

7.315647908504083

In [ ]:
env.force_mag = 10.0
states = []
actions = []

In [ ]:
count = 100000
count = 5
for i in range(count):
  force = random.uniform(-10.0, 10.0)
  if force>0: action = 1
  else: action = 0
  state = env.state
  states.append(state)
  actions.append(force)
  env.force_mag = force

  observation, reward, done, info =  env.step(action)
  if done:
    env.reset()



In [ ]:
states = np.array(states)
actions = np.array(actions).reshape((count,1))

In [ ]:
print(states.shape)
print(actions.shape)

(5, 4)
(5, 1)


In [ ]:
input = np.concatenate ((states, actions), axis  = 1)[:-1,:]
output = states.copy()[1:,:]

In [ ]:
print(input.shape)
print(output.shape)

(4, 5)
(4, 4)


In [ ]:
AtA = np.matmul(input.T, input)
AtA

array([[ 9.57374227e-03, -4.74256593e-02, -1.43042069e-03,
         8.71801093e-02, -6.20017363e-01],
       [-4.74256593e-02,  4.59202625e-01,  5.67493783e-04,
        -7.70703150e-01,  1.95669021e+00],
       [-1.43042069e-03,  5.67493783e-04,  4.24633709e-04,
        -3.14295524e-03,  1.14055834e-01],
       [ 8.71801093e-02, -7.70703150e-01, -3.14295524e-03,
         1.30586418e+00, -3.97933345e+00],
       [-6.20017363e-01,  1.95669021e+00,  1.14055834e-01,
        -3.97933345e+00,  5.13551541e+01]])

In [ ]:
x = solve(input, output)

ValueError: ignored

In [ ]:
np.linalg.inv(AtA)

array([[-5.35458007e+16,  3.00559934e+16, -5.40014070e+16,
         2.10626496e+16, -3.96282024e+13],
       [ 3.00559934e+16, -1.68708420e+16,  3.03117315e+16,
        -1.18227546e+16,  2.22438544e+13],
       [-5.40014070e+16,  3.03117315e+16, -5.44608898e+16,
         2.12418658e+16, -3.99653877e+13],
       [ 2.10626496e+16, -1.18227546e+16,  2.12418658e+16,
        -8.28515409e+15,  1.55880561e+13],
       [-3.96282024e+13,  2.22438544e+13, -3.99653877e+13,
         1.55880561e+13, -2.93280594e+10]])

In [ ]:
matrix_A = np.matmul(np.linalg.inv(AtA), input.T)
matrix_A = np.matmul(matrix_A, output)

In [ ]:
matrix_A = np.swapaxes(matrix_A,0,1)
matrix_A.shape

(4, 5)

In [ ]:
matrix_A.shape

(4, 5)

In [ ]:
final_B = matrix_A[:,-1]

In [ ]:
final_A = np.delete(matrix_A, -1, axis=1)

In [ ]:
final_A

array([[ 0.64637905,  0.11102189, -0.17543685,  0.08023501],
       [-2.81804314,  0.74275193, -2.87052554,  0.09048213],
       [ 0.03283145, -0.00813484,  1.02718452, -0.00769815],
       [ 5.90938433, -0.74658413,  6.60253324,  0.07683999]])

In [ ]:
final_B = final_B.reshape((4,1))
final_B

array([[ 6.24799825e-06],
       [-2.11979988e-03],
       [ 7.00043900e-05],
       [ 4.91233698e-03]])

In [ ]:
state_temp = states[0].reshape((4,1))
action_temp = actions[0].reshape(1,1)

In [ ]:
new_state = np.matmul(final_A, state_temp) + np.matmul(final_B, action_temp)
print(new_state)

[[-0.04243876]
 [ 0.06565159]
 [ 0.01324465]
 [-0.16376096]]


In [ ]:
states[1]

array([-0.052318  ,  0.16190329,  0.01282549, -0.32622625])

In [ ]:
np.matmul(matrix_A, input[0])

array([-0.04243876,  0.06565159,  0.01324465, -0.16376096])

In [ ]:
sta